### ISSUE TITLE
bounding box coordinates are mandatory

### ISSUE THREAD

**Issue by archaeogeek** [AstunTechnology/iso19139.gemini23#1]
These need to be shown as mandatory in default view, and also prevented from deletion https://www.agi.org.uk/agi-groups/standards-committee/uk-gemini/40-gemini/1062-gemini-datasets-and-data-series#44

**Comment by josegar74** [comment]
@archaeogeek, for the mandatory condition required CSS changes and update of the template handling that element in iso19139 schema.

We can add the template to GEMINI 2.3 schema, but for now as were required also CSS changes I've committed the changes to iso19139 in https://github.com/AstunTechnology/custom-geonetwork/commit/fc3ab17bd4123fca24fe5edf2bce1dbc2da1be71

About the removal of the element, the problem is that the max cardinality is N, if we prevent to delete it, none of the elements in case having several bboxes can be deleted. 

2 alternatives:

- Add an Add button.
- Use inflate mechanism as done in https://github.com/AstunTechnology/iso19139.gemini23/issues/9. 

If it's a mandatory element that should be present at least once I think is better the 2on option. Let me know what sounds better.

**Comment by archaeogeek** [comment]
@josegar74 I like the way that the inflate mechanism works, so would like to go for that option please

**Comment by josegar74** [comment]
Fixed, the code checks for `gmd:geographicElement/gmd:EX_GeographicBoundingBox` and if it's not available adds it to the first `gmd:extent` section.

Note that uses the default coordinates as in the template provided with the schema, to review if this is  ok or should be changed.

**Comment by archaeogeek** [comment]
Perfect, thanks
