### ISSUE TITLE
If it's not present already, there should be a spatial ref picker in default view for datasets and services

### ISSUE THREAD

**Issue by archaeogeek** [AstunTechnology/iso19139.gemini23#13]

**Comment by archaeogeek** [comment]
@josegar74 could you look at this one for me? I can't understand why spatial reference system doesn't show if missing in the default view. Ideally it should have a spatial reference picker like it does in advanced view.

**Comment by josegar74** [comment]
@archaeogeek the CRS picker uses geotools to search the CRS, but the information returned seem not according to what GEMINI 2.3 expects: https://www.agi.org.uk/agi-groups/standards-committee/uk-gemini/40-gemini/1062-gemini-datasets-and-data-series#17

This is what returns the current service:

`
 {
        "code": "27700",
        "authority": "European Petroleum Survey Group",
        "version": "8.6",
        "codeSpace": "EPSG",
        "description": "OSGB 1936 / British National Grid (EPSG:27700)"
    }
`

What is required for the `xlink:href` is `http://www.opengis.net/def/crs/EPSG/0/27700`, if the prefix `http://www.opengis.net/def/crs/EPSG/0/` is fixed we can calculated, but will require also some javascript changes outside of the schema as for now the xml snippet doesn't use anchors.

Please confirm this:

1) The `xlink:href` value can is always the prefix `http://www.opengis.net/def/crs/EPSG/0/` and the code returned by the current service?

2) Do we need to support Anchor instead of CharacterString?

Will check in the meantime why the simple view doesn't display the picker.

**Comment by archaeogeek** [comment]
@josegar74 
1) I think so
2) The guidelines say "When the provided text is a term or code from an externally defined explanation or registry value, gmx:Anchor should be used instead of gco:CharacterString"
Basically this should work the same way as for Gemini 2.2 and I'm confused as to why it doesn't?

**Comment by josegar74** [comment]
You mean in GEMINI 2.2 it uses the CRS picker and creates an Anchor?

**Comment by josegar74** [comment]
Committed a change in the editor configuration to display the CRS picker.

Pending to create Anchor elements instead, this will require a change in Javascript to be integrated in `master`, not in the metadata schema

**Comment by josegar74** [comment]
@archaeogeek  I was checking to support both text and anchor, but found in `master` the code is supporting anchors already, as the profile only requires anchor not really required to support both.

Please check to backport to your `3.4.x` branch the following commit: https://github.com/geonetwork/core-geonetwork/commit/63ace3d0d7f951229a8270932d7e3d78c69ac801

**Comment by archaeogeek** [comment]
@josegar74 this is now working, thanks. I'll close it.
