### ISSUE TITLE
Lay out distribution format in a table with suggestions dropdown

### ISSUE THREAD

**Issue by archaeogeek** [AstunTechnology/iso19139.gemini23#34]

**Comment by archaeogeek** [comment]
@josegar74 I've managed to get the distribution format laid out in a table, the same as the online resource, but I'm trying to implement the "add distribution format" button, and it doesn't have a suggestions list for the name. I think it should work the same way that gmd:protocol does in the resource locator block, but I can't see what I'm doing wrong. Could you take a look for me please?

**Comment by josegar74** [comment]
@archaeogeek I debugged the code that obtains the label configuration and in table mode see the following:

```
#gn-fn-metadata:getLabel
#Element name: gmd:name
#XPath: /gmd:MD_Metadata/gmd:distributionInfo/gmd:MD_Distribution/gmd:distributionFormat/gmd:MD_Format/gmd:name
#Parent: col
```

Parent should be `gmd:MD_Format` instead of `col` to match the `context` in:

https://github.com/AstunTechnology/iso19139.gemini23/blob/e677f32079d4cce699f907926a9c0f9305655680/src/main/plugin/iso19139.gemini23/loc/eng/labels.xml#L1595

But seem the parent element is not evaluated properly in the table mode.

Updating the file `labels.xml` to use in `context` instead of the parent element name the full xpath works:

```
<element name="gmd:name" context="/gmd:MD_Metadata/gmd:distributionInfo/gmd:MD_Distribution/gmd:distributionFormat/gmd:MD_Format/gmd:name" id="285.0" >
```

The only drawback is that some elements have `gmd:version` as related value, and in the table mode is not assigned. Will check a bit more, but probably not critical.

Please try at your end.

**Comment by archaeogeek** [comment]
that fixed it, thanks
