### ISSUE TITLE
Errors relating to schematron in logs

### ISSUE THREAD

**Issue by archaeogeek** [AstunTechnology/iso19139.gemini23#55]
I'm seeing the following errors in the log files and don't know if they are important or not:

```
Warning: on line 2539 of schematron-rules-GEMINI_2.3_Schema-v1.0.xsl:
  The child axis starting at an attribute node will never select anything
Warning: on line 2549 of schematron-rules-GEMINI_2.3_Schema-v1.0.xsl:
  The child axis starting at an attribute node will never select anything
Warning: on line 4981 of schematron-rules-GEMINI_2.3_Schema-v1.0.xsl:
  The child axis starting at an attribute node will never select anything
Warning: on line 4992 of schematron-rules-GEMINI_2.3_Schema-v1.0.xsl:
  The child axis starting at an attribute node will never select anything
Warning: on line 376 of schematron-rules-GEMINI_2.3_supp-v1.0.xsl:
  The child axis starting at an attribute node will never select anything
Warning: on line 386 of schematron-rules-GEMINI_2.3_supp-v1.0.xsl:
  The child axis starting at an attribute node will never select anything
```

Do they matter?

**Comment by josegar74** [comment]
The first 2 errors are caused by this rule (the others should be also due to similar rules):

https://github.com/AstunTechnology/iso19139.gemini23/blob/dea5810888cfd05004f144fe0ebd4400fcaed29e/src/main/plugin/iso19139.gemini23/schematron/schematron-rules-GEMINI_2.3_Schema-v1.0.sch#L450-L460

The problem is that the rule matches an attribute `xlink:href`, and this line uses `parent` on an attribute element, so the `sch:report` will not be executed properly:

https://github.com/AstunTechnology/iso19139.gemini23/blob/dea5810888cfd05004f144fe0ebd4400fcaed29e/src/main/plugin/iso19139.gemini23/schematron/schematron-rules-GEMINI_2.3_Schema-v1.0.sch#L456

I have check to update the rule without the attribute to use `"//gmd:MD_Metadata[1]/gmd:referenceSystemInfo/*[1]/gmd:referenceSystemIdentifier/gmd:RS_Identifier[1]/gmd:code/gmx:Anchor[1]`, but that overlaps with this:

https://github.com/AstunTechnology/iso19139.gemini23/blob/dea5810888cfd05004f144fe0ebd4400fcaed29e/src/main/plugin/iso19139.gemini23/schematron/schematron-rules-GEMINI_2.3_Schema-v1.0.sch#L473-L481

---

What is the purpose of each rule? 

  - The first one seem to check the attribute `xlink:href` of the first `gmx:Anchor`, but the index `[1]` should not be required as the cardinality is 1.

  - The second one seem checking the content of the `gmx:Anchor`.

Both seem checking different values against a list of CRS codes, does it mean the value can be either in the attribute `xlink:href` or in the text of the related `gmx:Anchor`.

If that's the case I would add a unique rule for the `gmx:Anchor` and do both checks in the same rule. But need to have clear that I'm not misunderstanding this.

---

For the other rules are similar cases with other attributes:

- https://github.com/AstunTechnology/iso19139.gemini23/blob/dea5810888cfd05004f144fe0ebd4400fcaed29e/src/main/plugin/iso19139.gemini23/schematron/schematron-rules-GEMINI_2.3_Schema-v1.0.sch#L1098-L1107

- https://github.com/AstunTechnology/iso19139.gemini23/blob/dea5810888cfd05004f144fe0ebd4400fcaed29e/src/main/plugin/iso19139.gemini23/schematron/schematron-rules-GEMINI_2.3_supp-v1.0.sch#L58-L64

**Comment by archaeogeek** [comment]
These schematron files come from https://github.com/AGIGemini/Schematron so if there are ways in which we can rewrite the rules to avoid these errors then I think we should probably submit them as pull requests against that repository rather than just change ours. What do you think?

**Comment by josegar74** [comment]
I have done some tests with the `sch` file in OxygenXML and there's no issue there with the rule, but using the xslt generated by GeoNetwork from the `sch` I get the same issue as in GeoNetwork (something expected).

Will check if it's a issue in the conversion of `sch` to `xslt` and also will validate the same metadata in GeoNetwork and OxygenXML to check that the rule is ignored in GeoNetwork. 

In that case we can propose a change to the schematron to work better with GeoNetwork.

**Comment by archaeogeek** [comment]
@josegar74 have you had chance to look at this issue again yet? It would be good to know whether we need to propose a change in the original schematron

**Comment by josegar74** [comment]
@archaeogeek I'm going to check and will let you know if any change is required or it's a problem of the conversion from sch to xslt in GeoNetwork.

**Comment by josegar74** [comment]
I'm checking to update the rule to match the `gmx:Anchor` instead, but below there's already this rule:

https://github.com/AstunTechnology/iso19139.gemini23/blob/d8b9cde97f42ad97ce96f062cc2c1e1e0a862e9c/src/main/plugin/iso19139.gemini23/schematron/schematron-rules-GEMINI_2.3_Schema-v1.0.sch#L472-L481

This rule checks the Anchor text content, and I guess the rule causing the issue checks the Anchor `xlink:href` content, so if either the text or the attribute match a valid CRS, an `sch:report` is reported? If that's the use case I can check to unify the 2 checks in 1 rule I think.

https://github.com/AstunTechnology/iso19139.gemini23/blob/d8b9cde97f42ad97ce96f062cc2c1e1e0a862e9c/src/main/plugin/iso19139.gemini23/schematron/schematron-rules-GEMINI_2.3_Schema-v1.0.sch#L450-L460

**Comment by josegar74** [comment]
This rule checks boths the attribute and the text content and avoid the error:

```
 <sch:rule
      context="//gmd:MD_Metadata[1]/gmd:referenceSystemInfo/*[1]/gmd:referenceSystemIdentifier/gmd:RS_Identifier[1]/gmd:code/gmx:Anchor">

      <sch:report
        test="
          $defaultCRScodes//crs/text()[normalize-space(.) = normalize-space(current()/@xlink:href)] and
          count(parent::gmd:code/parent::gmd:RS_Identifier/child::gmd:codeSpace) &gt; 0"
      > MI-17b (Spatial Reference System): The coordinate reference system <sch:value-of
        select="normalize-space(current()/@xlink:href)"/> is listed in Default Coordinate Reference System
        Identifiers in Annex D.4. Such identifiers SHALL NOT use gmd:codeSpace </sch:report>

      <sch:report
        test="
          $defaultCRScodes//crs/text()[normalize-space(.) = normalize-space(current()/.)] and
          count(parent::gmd:code/parent::gmd:RS_Identifier/child::gmd:codeSpace) &gt; 0"
        > MI-17d (Spatial Reference System): The coordinate reference system <sch:value-of
          select="normalize-space(current()/.)"/> is listed in Default Coordinate Reference System
        Identifiers in Annex D.4. Such identifiers SHALL NOT use gmd:codeSpace </sch:report>
    </sch:rule>
```

If looks fine like this, I can apply to the other rules matching attributes.

**Comment by archaeogeek** [comment]
@josegar74 this doesn't seem to have made much difference, in that I'm still seeing the same number of errors:
```
Warning: on line 2539 of schematron-rules-GEMINI_2.3_Schema-v1.0.xsl:
  The child axis starting at an attribute node will never select anything
Warning: on line 2549 of schematron-rules-GEMINI_2.3_Schema-v1.0.xsl:
  The child axis starting at an attribute node will never select anything
Warning: on line 4969 of schematron-rules-GEMINI_2.3_Schema-v1.0.xsl:
  The child axis starting at an attribute node will never select anything
Warning: on line 4980 of schematron-rules-GEMINI_2.3_Schema-v1.0.xsl:
  The child axis starting at an attribute node will never select anything
Warning: on line 376 of schematron-rules-GEMINI_2.3_supp-v1.0.xsl:
  The child axis starting at an attribute node will never select anything
Warning: on line 386 of schematron-rules-GEMINI_2.3_supp-v1.0.xsl:
  The child axis starting at an attribute node will never select anything
```

I've attached my schematron file in case I haven't applied things correctly
[schematron-rules-GEMINI_2.3_Schema-v1.0.sch.txt](https://github.com/AstunTechnology/iso19139.gemini23/files/4245534/schematron-rules-GEMINI_2.3_Schema-v1.0.sch.txt)

**Comment by josegar74** [comment]
Attached the file I changed. The first 2 errors should not be displayed.
[schematron-rules-GEMINI_2.3_Schema-v1.0.sch.txt](https://github.com/AstunTechnology/iso19139.gemini23/files/4260762/schematron-rules-GEMINI_2.3_Schema-v1.0.sch.txt)

**Comment by archaeogeek** [comment]
@josegar74 I get the same result as you now, so the first error is for line 4971. Happy for you to make the rest of the changes needed

**Comment by archaeogeek** [comment]
@josegar74 I'll close this- I think you've got rid of all the errors, thanks!
