### ISSUE TITLE
AT-6 errors on validating WMS due to handling of nilreasons

### ISSUE THREAD

**Issue by archaeogeek** [AstunTechnology/iso19139.gemini23#68]
AT-6 errors for:
*    Conformance Result -> explanation
*    Format name and version
which I think might be related to the elements with nilreasons being expanded to include an empty characterstring (#35)

**Comment by josegar74** [comment]
I have updated the following rule that checks there's no elements with empty `gco:CharacterString`

https://github.com/AstunTechnology/iso19139.gemini23/blob/799ceb71f6b187381495de47e72d971a7aecb4c2/src/main/plugin/iso19139.gemini23/schematron/schematron-rules-GEMINI_2.3_Schema-v1.0.sch#L1218-L1225


to the following to check also `gco:nilReason`:
 
```
 <sch:pattern fpi="Gemini2-at6">
    <sch:title>Non-empty free text content</sch:title>
    <sch:p>Don't allow empty Free text gco:CharacterString or gmx:Anchor</sch:p>
    <sch:rule context="//gco:CharacterString | //gmx:Anchor">
      <sch:assert test="normalize-space(.) or string(../@gco:nilReason)"> AT-6: Free text elements should not be empty
      </sch:assert>
    </sch:rule>
  </sch:pattern>
```

Partially was caused by the inflate process, but also the original rule assumed `gco:CharacterString` was removed if empty, what is not true at least by default in GeoNetwork that creates elements like:

```
<gmd:explanation gco:nilReason="unknown">
  <gco:CharacterString/>
</gmd:explanation>
```

I'm not sure if the previous schematron file is created by other organisation, can you check if can propose to them the previous change. Otherwise, let me know to commit directly if looks fine.

**Comment by archaeogeek** [comment]
@josegar74 the original schematron is from https://github.com/AGIGemini/Schematron. I've contacted them and asked the best approach for proposing the changes. Please do commit your changes to our repository now though.

**Comment by archaeogeek** [comment]
@josegar74 the AGI Gemini working group would like you to submit a pull request for the changes you've made to the schematron so please go ahead. I will test these commits and let you know how I get on

**Comment by josegar74** [comment]
I committed the change, but seem some stuff with the editor that identifies all file changed, while the only change is this https://github.com/metadata101/iso19139.gemini23/commit/441f3b4c570dd14ad7cce4a86d26da382f0d1022#diff-3ea8e88e0625b58e40ed4508b0c8ecebR1222

Please provide to them or let me know if where is their repository and I can do a PR.

**Comment by archaeogeek** [comment]
@josegar74 this is the repository https://github.com/AGIGemini/Schematron to do a PR against, but because the names of the schematron in that repository don't match Geonetwork's requirements, I think you'll need to fork it and make the changes to their version. I could propose that the schematron files are renamed to match Geonetwork's requirements but that might not be acceptable.

**Comment by josegar74** [comment]
Ok, I'll fork it and do the PR

**Comment by josegar74** [comment]
See https://github.com/AGIGemini/Schematron/pull/1

**Comment by archaeogeek** [comment]
Great! I'll close this then
